# Generated by Django 5.2.5 on 2025-08-31 22:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCommissionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único usado em URLs públicas', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, help_text='Soma de todas as vendas do vendedor neste mês', max_digits=12, verbose_name='Total de Vendas no Mês (R$)')),
                ('sales_days_count', models.PositiveIntegerField(help_text='Quantidade de dias que o vendedor teve vendas neste mês', verbose_name='Dias com Vendas')),
                ('total_commission', models.DecimalField(decimal_places=2, help_text='Soma de todas as comissões calculadas do mês', max_digits=10, verbose_name='Comissão Total (R$)')),
                ('average_commission_rate', models.DecimalField(decimal_places=2, help_text='Snapshot da taxa média aplicada no período', max_digits=5, verbose_name='Taxa Média de Comissão (%)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Aprovação'), ('APPROVED', 'Aprovado para Pagamento'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('payment_notes', models.TextField(blank=True, verbose_name='Observações do Pagamento')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reports', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Relatório de Comissão Mensal',
                'verbose_name_plural': 'Relatórios de Comissão Mensais',
                'indexes': [models.Index(fields=['seller', 'year', 'month'], name='commissions_seller__85e2a9_idx'), models.Index(fields=['status', 'year', 'month'], name='commissions_status_51dfdc_idx'), models.Index(fields=['status', 'created_at'], name='commissions_status_b40183_idx')],
                'unique_together': {('seller', 'year', 'month')},
            },
        ),
    ]
