# Generated by Django 5.2.5 on 2025-09-02 03:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='average_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot da taxa média aplicada no período', max_digits=5, verbose_name='Taxa Média de Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='sales_days_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de dias que o vendedor teve vendas neste mês', verbose_name='Dias com Vendas'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todas as comissões calculadas do mês', max_digits=10, verbose_name='Comissão Total (R$)'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todas as vendas do vendedor neste mês', max_digits=12, verbose_name='Total de Vendas no Mês (R$)'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano'),
        ),
    ]
