# Generated by Django 5.2.5 on 2025-09-02 03:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_monthlycommissionreport_paid_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlycommissionreport',
            name='commissions_seller__85e2a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlycommissionreport',
            name='commissions_status_51dfdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlycommissionreport',
            name='commissions_status_b40183_idx',
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='average_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taxa Média de Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='sales_days_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias com Vendas'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comissão Total (R$)'),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Vendas no Mês (R$)'),
        ),
    ]
