# Generated by Django 5.2.5 on 2025-09-02 03:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_remove_monthlycommissionreport_commissions_seller__85e2a9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlycommissionreport',
            name='paid_by',
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='average_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='sales_days_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
