# Generated by Django 5.2.5 on 2025-09-02 03:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_remove_monthlycommissionreport_paid_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycommissionreport',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='month',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Aprovação'), ('APPROVED', 'Aprovado para Pagamento'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='monthlycommissionreport',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
