# Generated by Django 5.2.5 on 2025-08-30 18:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único usado em URLs públicas', unique=True, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sale_date', models.DateField(help_text='Data em que as vendas foram realizadas', verbose_name='Data das Vendas')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Soma de todas as vendas do vendedor neste dia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total Vendido (R$)')),
                ('commission_rate_applied', models.DecimalField(decimal_places=2, help_text='Taxa que foi aplicada no momento do lançamento (histórico)', max_digits=5, verbose_name='Taxa de Comissão Aplicada (%)')),
                ('calculated_commission', models.DecimalField(decimal_places=2, help_text='Valor da comissão = total_amount * commission_rate_applied', max_digits=8, verbose_name='Comissão Calculada (R$)')),
                ('notes', models.TextField(blank=True, help_text='Observações opcionais sobre as vendas do dia', verbose_name='Observações')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Usuário que fez o lançamento (pode ser o próprio vendedor ou gerente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_registered', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('seller', models.ForeignKey(help_text='Vendedor que realizou as vendas', on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda Diária',
                'verbose_name_plural': 'Vendas Diárias',
                'indexes': [models.Index(fields=['seller', 'sale_date'], name='sales_daily_seller__e2e4bf_idx'), models.Index(fields=['sale_date'], name='sales_daily_sale_da_f2bdae_idx'), models.Index(fields=['is_active', 'sale_date'], name='sales_daily_is_acti_fc219d_idx')],
                'unique_together': {('seller', 'sale_date')},
            },
        ),
    ]
