# Generated by Django 5.2.5 on 2025-08-31 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='calculated_commission',
            field=models.DecimalField(decimal_places=2, help_text='total_amount * (commission_rate_applied / 100)', max_digits=8, verbose_name='Comissão Calculada (R$)'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='commission_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa aplicada no momento do lançamento (mantém histórico)', max_digits=5, null=True, verbose_name='Taxa de Comissão Aplicada (%)'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez o lançamento (vendedor ou gerente/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_registered', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por'),
        ),
    ]
